
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DBEntity
{

using System;
    using System.Collections.Generic;
    
public partial class Doc
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Doc()
    {

        this.CauHois = new HashSet<CauHoi>();

    }


    public int ID { get; set; }

    public string DoanVan { get; set; }

    public Nullable<int> IDChuDe { get; set; }



    public virtual ChuDe ChuDe { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CauHoi> CauHois { get; set; }

}

}
